# -*- coding: utf-8 -*-
"""Venta_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4GvVsHpyfXX-Kl12GiO-FTf8TZWYkJx
"""

streamlit_code = """import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# Configuración de la página
st.set_page_config(
    page_title="Dashboard de Ventas",
    page_icon="📊",
    layout="wide"
)

st.title("📊 Dashboard de Análisis de Ventas")
st.markdown("---")

# Sidebar para filtros
st.sidebar.header("🔍 Filtros")

# Generar datos de ejemplo
@st.cache_data
def generar_datos():
    np.random.seed(42)
    fechas = pd.date_range(start='2026-01-01', end='2026-12-31', freq='D')

    productos = ['Laptop', 'Mouse', 'Teclado', 'Monitor', 'Webcam']
    regiones = ['Norte', 'Sur', 'Este', 'Oeste', 'Centro']

    datos = []
    for fecha in fechas:
        for _ in range(np.random.randint(5, 15)):
            datos.append({
                'Fecha': fecha,
                'Producto': np.random.choice(productos),
                'Región': np.random.choice(regiones),
                'Cantidad': np.random.randint(1, 10),
                'Precio_Unitario': np.random.randint(20, 500),
            })

    df = pd.DataFrame(datos)
    df['Total'] = df['Cantidad'] * df['Precio_Unitario']
    return df

df = generar_datos()

# Filtros
productos_seleccionados = st.sidebar.multiselect(
    "Selecciona Productos:",
    options=df['Producto'].unique(),
    default=df['Producto'].unique()
)

regiones_seleccionadas = st.sidebar.multiselect(
    "Selecciona Regiones:",
    options=df['Región'].unique(),
    default=df['Región'].unique()
)

# Aplicar filtros
df_filtrado = df[
    (df['Producto'].isin(productos_seleccionados)) &
    (df['Región'].isin(regiones_seleccionadas))
]

# Métricas principales
st.header("📈 Métricas Principales")
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Ventas Totales", f"${df_filtrado['Total'].sum():,.0f}")

with col2:
    st.metric("Ticket Promedio", f"${df_filtrado['Total'].mean():,.0f}")

with col3:
    st.metric("Productos Vendidos", f"{df_filtrado['Cantidad'].sum():,}")

with col4:
    mejor_producto = df_filtrado.groupby('Producto')['Total'].sum().idxmax()
    st.metric("Producto Top", mejor_producto)

st.markdown("---")

# Gráficos
col_left, col_right = st.columns(2)

with col_left:
    st.subheader("📊 Ventas por Producto")
    ventas_producto = df_filtrado.groupby('Producto')['Total'].sum().reset_index()
    fig = px.bar(ventas_producto, x='Producto', y='Total', color='Total')
    st.plotly_chart(fig, use_container_width=True)

with col_right:
    st.subheader("🗺️ Ventas por Región")
    ventas_region = df_filtrado.groupby('Región')['Total'].sum().reset_index()
    fig = px.pie(ventas_region, values='Total', names='Región', hole=0.4)
    st.plotly_chart(fig, use_container_width=True)

# Tendencia temporal
st.subheader("📈 Tendencia de Ventas")
ventas_tiempo = df_filtrado.groupby('Fecha')['Total'].sum().reset_index()
fig = px.line(ventas_tiempo, x='Fecha', y='Total', markers=True)
st.plotly_chart(fig, use_container_width=True)

# Datos
st.subheader("📋 Datos Detallados")
st.dataframe(df_filtrado.head(100), use_container_width=True)
"""

# Guarda el contenido de Streamlit en un archivo llamado 'app.py'
with open('app.py', 'w') as f:
    f.write(streamlit_code)